<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Emily Han (emh006@ucsd.edu)">
<meta name="dcterms.date" content="2024-12-10">

<title>Replication of Study ‘How Quick Decisions Illuminate Moral Character’ by Clayton R. Critcher, Yoel Inbar and David A. Pizarro (2013, Social Psychological and Personality Science)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="emily_han_writeup_files/libs/clipboard/clipboard.min.js"></script>
<script src="emily_han_writeup_files/libs/quarto-html/quarto.js"></script>
<script src="emily_han_writeup_files/libs/quarto-html/popper.min.js"></script>
<script src="emily_han_writeup_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="emily_han_writeup_files/libs/quarto-html/anchor.min.js"></script>
<link href="emily_han_writeup_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="emily_han_writeup_files/libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="emily_han_writeup_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="emily_han_writeup_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="emily_han_writeup_files/libs/bootstrap/bootstrap-677b520d69fcc55ab41b4b425631e74d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods">Methods</a>
  <ul class="collapse">
  <li><a href="#power-analysis" id="toc-power-analysis" class="nav-link" data-scroll-target="#power-analysis">Power Analysis</a></li>
  <li><a href="#planned-sample" id="toc-planned-sample" class="nav-link" data-scroll-target="#planned-sample">Planned Sample</a></li>
  <li><a href="#materials" id="toc-materials" class="nav-link" data-scroll-target="#materials">Materials</a></li>
  <li><a href="#procedure" id="toc-procedure" class="nav-link" data-scroll-target="#procedure">Procedure</a></li>
  <li><a href="#design-overview" id="toc-design-overview" class="nav-link" data-scroll-target="#design-overview">Design Overview</a></li>
  <li><a href="#differences-from-original-study" id="toc-differences-from-original-study" class="nav-link" data-scroll-target="#differences-from-original-study">Differences from Original Study</a></li>
  <li><a href="#methods-addendum-post-data-collection" id="toc-methods-addendum-post-data-collection" class="nav-link" data-scroll-target="#methods-addendum-post-data-collection">Methods Addendum (Post Data Collection)</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data preparation</a></li>
  <li><a href="#confirmatory-analysis" id="toc-confirmatory-analysis" class="nav-link" data-scroll-target="#confirmatory-analysis">Confirmatory analysis</a></li>
  </ul></li>
  <li><a href="#exploratory-analysis" id="toc-exploratory-analysis" class="nav-link" data-scroll-target="#exploratory-analysis">Exploratory Analysis</a>
  <ul class="collapse">
  <li><a href="#analysis-on-perceived-certainty" id="toc-analysis-on-perceived-certainty" class="nav-link" data-scroll-target="#analysis-on-perceived-certainty">Analysis on perceived certainty</a>
  <ul class="collapse">
  <li><a href="#visualization-1" id="toc-visualization-1" class="nav-link" data-scroll-target="#visualization-1">Visualization</a></li>
  </ul></li>
  <li><a href="#post-hoc-effect-size-calculation" id="toc-post-hoc-effect-size-calculation" class="nav-link" data-scroll-target="#post-hoc-effect-size-calculation">Post Hoc &amp; Effect size calculation</a>
  <ul class="collapse">
  <li><a href="#effect-size-calculation-on-both-moral-character-evaluation-decision-certainty-evaluation-tests" id="toc-effect-size-calculation-on-both-moral-character-evaluation-decision-certainty-evaluation-tests" class="nav-link" data-scroll-target="#effect-size-calculation-on-both-moral-character-evaluation-decision-certainty-evaluation-tests">Effect Size Calculation on both Moral Character Evaluation &amp; Decision Certainty Evaluation tests</a></li>
  </ul></li>
  <li><a href="#post-hoc-comparison-of-all-three-2x2-anova-tests" id="toc-post-hoc-comparison-of-all-three-2x2-anova-tests" class="nav-link" data-scroll-target="#post-hoc-comparison-of-all-three-2x2-anova-tests">Post-Hoc Comparison of all three 2x2 Anova Tests</a>
  <ul class="collapse">
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#summary-of-replication-attempt" id="toc-summary-of-replication-attempt" class="nav-link" data-scroll-target="#summary-of-replication-attempt">Summary of Replication Attempt</a></li>
  <li><a href="#commentary" id="toc-commentary" class="nav-link" data-scroll-target="#commentary">Commentary</a></li>
  </ul></li>
  <li><a href="#statement-of-contributions" id="toc-statement-of-contributions" class="nav-link" data-scroll-target="#statement-of-contributions">Statement of Contributions</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Replication of Study ‘How Quick Decisions Illuminate Moral Character’ by Clayton R. Critcher, Yoel Inbar and David A. Pizarro (2013, Social Psychological and Personality Science)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Emily Han (emh006@ucsd.edu) </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 10, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This report presents our replication of the study “How Quick Decisions Illuminate Moral Character” conducted by Critcher, Inbar, and Pizarro (2013), which examined the effect of decision speed on judgments of moral character. The original study found that individuals who made quick moral decisions were evaluated more positively, whereas those who made quick immoral decisions were judged more harshly. In contrast, slower decisions, whether moral or immoral, led to more moderate evaluations of character. The authors proposed that quick decisions are seen as more certain and, therefore, more revealing of the decision maker’s underlying motives.</p>
<p>The original study employed two experiments. The first involved participants evaluating two individuals’ moral character, one who made a quick decision and another who took longer to decide, in both ethical and unethical contexts. The second experiment explored a similar structure but focused on more complex moral dilemmas. Both experiments consistently showed that quick decisions amplified moral evaluations, with quick moral decisions being judged more favorably and quick immoral decisions being judged more harshly.</p>
<p>Our replication aimed to reproduce the findings of the first experiment by closely following the original methodology. Specifically, we focused on testing whether decision speed continued to amplify moral character judgments, with quick decisions leading to more polarized evaluations compared to slower ones. This replication project is part of a broader effort to assess the robustness of psychological research through reproducibility studies.</p>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<section id="power-analysis" class="level3">
<h3 class="anchored" data-anchor-id="power-analysis">Power Analysis</h3>
<p>In the absence of prior data or specific effect size estimates from our study to conduct a traditional power analysis, we followed standard practice and increased our original sample size of 119 by a factor of 2.5, setting a target of 298 participants. This approach was intended to ensure adequate power to detect effects across conditions, compensating for the lack of data.</p>
</section>
<section id="planned-sample" class="level3">
<h3 class="anchored" data-anchor-id="planned-sample">Planned Sample</h3>
<p>For our replication experiment, we would require a sample size of 298 participants. In the original study, the participants were students from the University of California, Berkeley or members from the nearby community who were randomly assigned to different conditions to assess the influence of decision speed on moral evaluations. However, participants for this replication study were recruited through Prolific and screened to ensure they reside in the US and are fluent in English.</p>
</section>
<section id="materials" class="level3">
<h3 class="anchored" data-anchor-id="materials">Materials</h3>
<p>All the materials for this replication study come from the original study, <em>How Quick Decisions Illuminate Moral Character</em>, conducted by Critcher, Inbar, and Pizarro (2013). Our paradigm can be found <a href="https://ucsd-psych201a.github.io/critcher2013_3/">here</a>.</p>
<section id="scenario" class="level4">
<h4 class="anchored" data-anchor-id="scenario">Scenario:</h4>
<p>Participants were randomly assigned to one of two conditions: moral or immoral. Within each condition, two agents, Justin and Nate, were presented, differing in their decision-making speed.</p>
<ul>
<li><p><strong>Moral Condition</strong>: In separate instances, Justin and Nate encounter a cash-filled wallet in a grocery store parking lot. Justin quickly decides to return the wallet to customer service rather than keeping the money. Nate ultimately makes the same decision, but only after a prolonged period of deliberation.</p></li>
<li><p><strong>Immoral Condition</strong>: In separate instances, Justin and Nate find a cash-filled wallet in a grocery store parking lot. Justin quickly decides to take the money and leave. Nate reaches the same conclusion but only after taking a long time to decide.</p></li>
</ul>
</section>
<section id="questionnaire" class="level4">
<h4 class="anchored" data-anchor-id="questionnaire">Questionnaire:</h4>
<p>Participants were asked to answer the following questions based on their evaluation of each agent, Justin and Nate. Each question corresponds to one of the categories below, with its own specific scale.</p>
<section id="quickness" class="level5">
<h5 class="anchored" data-anchor-id="quickness">Quickness:</h5>
<ol type="1">
<li>Did [name] make his decision quickly or slowly?<br>
<strong>Scale:</strong> 1 = particularly slowly, 7 = particularly quickly</li>
</ol>
</section>
<section id="moral-character-evaluation" class="level5">
<h5 class="anchored" data-anchor-id="moral-character-evaluation">Moral character evaluation:</h5>
<ol start="2" type="1">
<li><p>Regardless of [name]’s decision, does it sound like [name] has underlying moral principles that are good, bad, or somewhere in between?<br>
<strong>Scale:</strong> 1 = completely bad, 4 = mixed, 7 = completely good</p></li>
<li><p>Regardless of [name]’s decision, do you think [name] has moral standards that are good, bad, or somewhere in between?<br>
<strong>Scale:</strong> 1 = completely bad, 4 = mixed, 7 = completely good</p></li>
<li><p>Regardless of [name]’s decision, do you think [name] possesses the moral knowledge and principles necessary to do ‘the right thing’?<br>
<strong>Scale:</strong> 1 = not at all, 4 = somewhat, 7 = completely</p></li>
</ol>
</section>
<section id="certainty" class="level5">
<h5 class="anchored" data-anchor-id="certainty">Certainty:</h5>
<ol start="5" type="1">
<li><p>Would you say [name] was quite certain in his decision, or did [name] have hesitations about his decision?<br>
<strong>Scale:</strong> 1 = completely certain, 7 = considerable hesitations</p></li>
<li><p>How close do you think [name] was to choosing the alternate course of action?<br>
<strong>Scale:</strong> 1 = very close to, 7 = not close at all</p></li>
<li><p>How conflicted do you think [name] felt in making the decision?<br>
<strong>Scale:</strong> 1 = very conflicted, 7 = not at all conflicted</p></li>
<li><p>Based on the information provided, do you think [name] had many reservations about the decision?<br>
<strong>Scale:</strong> 1 = none at all, 7 = a whole lot</p></li>
</ol>
</section>
<section id="emotional-impulsivity" class="level5">
<h5 class="anchored" data-anchor-id="emotional-impulsivity">Emotional impulsivity:</h5>
<ol start="9" type="1">
<li><p>Do you think [name] was calm and emotionally contained while making the decision?<br>
<strong>Scale:</strong> 1 = not at all, 7 = entirely so</p></li>
<li><p>To what extent do you think [name] became upset and acted without thinking?<br>
<strong>Scale:</strong> 1 = not at all, 7 = entirely so</p></li>
</ol>
</section>
</section>
</section>
<section id="procedure" class="level3">
<h3 class="anchored" data-anchor-id="procedure">Procedure</h3>
<p>As in the original experiment (Critcher et al., 2013), our paradigm followed this procedure: “Participants read about Justin and Nate, two men who each independently came upon cash-filled wallets in the parking lot of a local grocery store”. Justin ‘was able to decide quickly’ what to do, while Nate ‘was only able to decide after long and careful deliberation.’ Participants assigned to the moral condition learned that both men ‘did not steal the money but instead left the wallet with customer service.’ Those in the immoral condition learned that both men ‘pocketed the money and drove off.’”</p>
<p>Adhering to the procedures outlined by Critcher et al.&nbsp;(2013), after reading the scenario of Justin and Nate’s actions, participants completed four Likert-scale assessments, each scaled from 1 to 7. The first assessment evaluated the quickness of the actors’ decisions (manipulation check). The second assessed Justin and Nate’s morality, with items such as: “has entirely good (vs.&nbsp;entirely bad) moral principles,” “has good (vs.&nbsp;bad) moral standards,” and “deep down has the moral principles and knowledge to do the right thing.” The third assessment included four items evaluating the certainty of the actors’ decisions, such as: “how conflicted [each] felt when making his decision,” “how many reservations [each] had,” “was quite certain in his decision,” and “how far [each] was from choosing the alternate course of action.” Finally, the fourth assessment evaluated perceived emotional impulsivity, asking whether the actors were “calm and emotionally contained” or “upset and acted without thinking.”</p>
</section>
<section id="design-overview" class="level3">
<h3 class="anchored" data-anchor-id="design-overview">Design Overview</h3>
<section id="factors" class="level4">
<h4 class="anchored" data-anchor-id="factors">Factors</h4>
<p>In this replication study, two factors were manipulated: participants were randomly assigned to a condition (moral vs.&nbsp;immoral), and within each condition, they were exposed to both scenarios where one actor made the decision quickly (moral or immoral), and the other made the same decision slowly.</p>
</section>
<section id="primary-measures" class="level4">
<h4 class="anchored" data-anchor-id="primary-measures">Primary Measures</h4>
<p>Four primary measures were collected from participants:</p>
<ol type="1">
<li><p><strong>Quickness of Decision</strong>: A manipulation check assessing participants’ perceptions of how quickly Justin and Nate made their decisions (e.g., “Did [name] make his decision quickly or slowly?”).</p></li>
<li><p><strong>Moral Character Evaluation</strong>: Participants rated each agent’s moral principles and standards using items such as, “Does [name] have underlying moral principles that are good, bad, or somewhere in between?” and “Does [name] possess the moral knowledge and principles necessary to do the right thing?”</p></li>
<li><p><strong>Certainty</strong>: Four items evaluated participants’ perceptions of each agent’s certainty in their decision, including “How conflicted [name] felt when making the decision” and “How close [name] was to choosing the alternate course of action.”</p></li>
<li><p><strong>Emotional Impulsivity</strong>: Two items assessed perceptions of each agent’s emotional impulsivity, such as “Was [name] calm and emotionally contained?” and “Did [name] become upset and act without thinking?”</p></li>
</ol>
</section>
<section id="mixed-design" class="level4">
<h4 class="anchored" data-anchor-id="mixed-design">Mixed Design</h4>
<p>The replication study reflects the original study’s mixed design:</p>
<ul>
<li><strong>Between-Subjects Factor</strong>:
<ul>
<li><strong>Moral Condition (moral vs.&nbsp;immoral)</strong>: Participants were randomly assigned to one of two conditions—moral (where both characters return the wallet) or immoral (where both characters keep the wallet). Each participant experienced only one of these conditions, making this factor between-subjects.</li>
</ul></li>
<li><strong>Within-Subjects Factor</strong>:
<ul>
<li><strong>Decision Speed (quick vs.&nbsp;deliberative)</strong>: Each participant evaluated both Justin (quick decision) and Nate (deliberative decision). Because every participant observed and evaluated both decision speeds within their assigned condition, this factor is within-subjects.</li>
</ul></li>
</ul>
</section>
<section id="impact-of-switching-between--and-within-subjects-designs" class="level4">
<h4 class="anchored" data-anchor-id="impact-of-switching-between--and-within-subjects-designs">Impact of Switching Between- and Within-Subjects Designs</h4>
<p>Although this replication followed the original study’s mixed design, switching both factors (decision and speed) to either a fully within-subjects or fully between-subjects design is a possible choice.</p>
<p>A fully within-subjects design could increase statistical power and require fewer participants, as each person would experience all combinations of conditions (quick/slow and moral/immoral). This design reduces variability due to individual differences, making it easier to detect effects. However, it could also risk carryover effects, where experiencing one condition might influence responses in the next, potentially producing biased results. Additionally, participants may guess the study’s purpose and alter their responses to appear consistent or meet the experiment’s expectations.</p>
<p>In contrast, in a fully between-subjects design, each participant would experience only one combination of decision speed and moral condition, requiring a larger sample size to achieve reliable effects. With only one condition per participant, variability due to individual differences is higher, which reduces statistical power and sensitivity to detect effects. However, this design minimizes potential biases, such as carryover effects and demand characteristics, as participants encounter only one scenario.</p>
</section>
<section id="potential-confounding-variables" class="level4">
<h4 class="anchored" data-anchor-id="potential-confounding-variables">Potential Confounding Variables</h4>
<p>Potential confounding variables in this study include but are not limited to participants’ own biases and preconceptions about the decision-making process, which can manifest as personal perceptions of quick versus slow decisions and overall moral judgments. Another important confound relates to preconceptions about men’s moral character, as both characters in the scenario are male, and participants may carry implicit gender biases that influence their evaluations. Additionally, cultural perspectives, participants’ emotional states and contexts, as well as the moral complexity of the scenarios, may further impact these judgments.</p>
</section>
</section>
<section id="differences-from-original-study" class="level3">
<h3 class="anchored" data-anchor-id="differences-from-original-study">Differences from Original Study</h3>
<p>This replication differs from the original study primarily in the participant sample and mode of data collection. Participants for this replication were recruited through the online platform Prolific, rather than from a local population at a university. Consequently, this replication was conducted entirely online and targeted a sample size of 300 participants, larger than the original sample of 119. Additionally, this replication focused exclusively on Experiment 1 from the original study and did not include subsequent experiments.</p>
</section>
<section id="methods-addendum-post-data-collection" class="level3">
<h3 class="anchored" data-anchor-id="methods-addendum-post-data-collection">Methods Addendum (Post Data Collection)</h3>
<section id="actual-sample" class="level4">
<h4 class="anchored" data-anchor-id="actual-sample">Actual Sample</h4>
<p>For our replication experiment, we would require at least a sample size of 298 participants. In the original study, the 119 participants were students from the University of California, Berkeley or members from the nearby community who were randomly assigned to different conditions to assess the influence of decision speed on moral evaluations. However, participants for this replication study will be recruited through the data collection platform, Prolific, and only screened for residing in the US and being fluent in English.</p>
</section>
<section id="differences-from-pre-data-collection-methods-plan" class="level4">
<h4 class="anchored" data-anchor-id="differences-from-pre-data-collection-methods-plan">Differences from pre-data collection methods plan</h4>
<p>Within the CSS 204 course, three independent teams worked on replicating Critcher, Inbar, and Pizarro’s study, each conducting separate data collection efforts. Combined, these efforts aligned with the target sample size of 300 specified in our planned power analysis (rounded from 298). To facilitate the analysis, our Teaching Assistant, Janna Wennberg, merged the cleaned datasets from all three teams. She carefully organized the data to ensure consistency and accuracy for our individual analyses. This combined dataset provided greater statistical power and a broader participant base, while still allowing for comparisons between the combined dataset and the individual datasets collected by our team.</p>
<p>For this analysis, we used both the merged dataset and the individual dataset specific to our group (group 3) to run our confirmatory analysis: 2x2 Anova. Additionally, we reverse-coded items related to decision certainty (from our combined dataset) to align with the original study’s methodology. These steps were implemented to ensure consistency across datasets and preserve the validity of our findings.</p>
</section>
</section>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">Data preparation</h3>
<p>Our replication of Experiment 1 will closely mirror the original study’s 2x2 factorial design, manipulating moral condition (stealing vs.&nbsp;not stealing) and decision speed (quick vs.&nbsp;slow). The dependent variable will be the moral character evaluation, assessed using a Likert scale. As in the original study, this replication will also examine perceived certainty of the actor in the scenario as covariates. The questionnaire items for the covariates will also be assessed using a Likert scale.</p>
<section id="raw-data-processing" class="level4">
<h4 class="anchored" data-anchor-id="raw-data-processing">Raw Data Processing</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">#### Load necessary libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effectsize)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix

Attaching package: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lmerTest'

The following object is masked from 'package:lme4':

    lmer

The following object is masked from 'package:stats':

    step</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the directory containing your CSV files</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>directory_path <span class="ot">&lt;-</span> <span class="st">"../data/final-data"</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize an empty tibble to store all cleaned data</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>cleaned_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>()</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a list of all CSV files in the directory</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>file_list <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="at">path =</span> directory_path, <span class="at">pattern =</span> <span class="st">"</span><span class="sc">\\</span><span class="st">.csv$"</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through each file in the directory</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (file <span class="cf">in</span> file_list) {</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Read the CSV file</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(file)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Flag to track if the attention check passes</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  attention_check_passed <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Check attention check questions</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>  attention_check_row <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(trial_type <span class="sc">==</span> <span class="st">"survey-html-form"</span>)</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Validate attention check</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(attention_check_row) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Parse the JSON string in the response column</span></span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>    attention_responses <span class="ot">&lt;-</span> jsonlite<span class="sc">::</span><span class="fu">fromJSON</span>(attention_check_row<span class="sc">$</span>response)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Define correct answers for attention check</span></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>    correct_answers <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>      <span class="st">"q1"</span> <span class="ot">=</span> <span class="st">"Justin and Nate"</span>,</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>      <span class="st">"q2"</span> <span class="ot">=</span> <span class="st">"A wallet"</span></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Check if all attention check answers are correct</span></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a>    attention_check_passed <span class="ot">&lt;-</span> <span class="fu">all</span>(</span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>      attention_responses<span class="sc">$</span>q1 <span class="sc">==</span> correct_answers<span class="sc">$</span>q1 <span class="sc">&amp;&amp;</span></span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>        attention_responses<span class="sc">$</span>q2 <span class="sc">==</span> correct_answers<span class="sc">$</span>q2</span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Process data only if attention check passes</span></span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (attention_check_passed) {</span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Select relevant columns (do not drop NAs here)</span></span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a>    temp_cleaned <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(condition, scenario, <span class="fu">starts_with</span>(<span class="st">"response_Q"</span>))</span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Determine who came first based on the first non-NA scenario entry</span></span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a>    temp_cleaned <span class="ot">&lt;-</span> temp_cleaned <span class="sc">%&gt;%</span></span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a>      <span class="fu">group_by</span>(condition) <span class="sc">%&gt;%</span></span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(</span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a>        <span class="at">first_scenario =</span> <span class="fu">first</span>(<span class="fu">na.omit</span>(scenario))  <span class="co"># Identify the first scenario for each participant</span></span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a>      ) <span class="sc">%&gt;%</span></span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a>      <span class="fu">ungroup</span>()</span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert condition to a factor for easier interpretation</span></span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a>    temp_cleaned <span class="ot">&lt;-</span> temp_cleaned <span class="sc">%&gt;%</span></span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(</span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a>        <span class="at">condition =</span> <span class="fu">factor</span>(condition, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"immoral"</span>, <span class="st">"moral"</span>)),</span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a>        <span class="at">scenario =</span> <span class="fu">factor</span>(scenario)</span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a>      ) <span class="sc">%&gt;%</span></span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Rearrange columns to place first_scenario after condition</span></span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(condition, first_scenario, scenario, <span class="fu">starts_with</span>(<span class="st">"response_Q"</span>))</span>
<span id="cb11-62"><a href="#cb11-62" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-63"><a href="#cb11-63" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Rename response columns to include scenario information</span></span>
<span id="cb11-64"><a href="#cb11-64" aria-hidden="true" tabindex="-1"></a>    temp_cleaned <span class="ot">&lt;-</span> temp_cleaned <span class="sc">%&gt;%</span></span>
<span id="cb11-65"><a href="#cb11-65" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Ensure no NA in 'scenario' or 'question' before combining</span></span>
<span id="cb11-66"><a href="#cb11-66" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(scenario)) <span class="sc">%&gt;%</span></span>
<span id="cb11-67"><a href="#cb11-67" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"response_Q"</span>),</span>
<span id="cb11-68"><a href="#cb11-68" aria-hidden="true" tabindex="-1"></a>                   <span class="at">names_to =</span> <span class="st">"question"</span>,</span>
<span id="cb11-69"><a href="#cb11-69" aria-hidden="true" tabindex="-1"></a>                   <span class="at">values_to =</span> <span class="st">"response"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-70"><a href="#cb11-70" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Remove rows where both 'question' and 'response' are NA</span></span>
<span id="cb11-71"><a href="#cb11-71" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(question) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(response)) <span class="sc">%&gt;%</span></span>
<span id="cb11-72"><a href="#cb11-72" aria-hidden="true" tabindex="-1"></a>      <span class="fu">unite</span>(<span class="st">"question_scenario"</span>, scenario, question, <span class="at">sep =</span> <span class="st">"_"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-73"><a href="#cb11-73" aria-hidden="true" tabindex="-1"></a>      <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> question_scenario, <span class="at">values_from =</span> response)</span>
<span id="cb11-74"><a href="#cb11-74" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb11-75"><a href="#cb11-75" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Append the cleaned data from this file to the main cleaned_data tibble</span></span>
<span id="cb11-76"><a href="#cb11-76" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Ensure rows with NAs are retained by not filtering them out</span></span>
<span id="cb11-77"><a href="#cb11-77" aria-hidden="true" tabindex="-1"></a>    cleaned_data <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(cleaned_data, temp_cleaned)</span>
<span id="cb11-78"><a href="#cb11-78" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb11-79"><a href="#cb11-79" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If attention check fails, log the file name (optional)</span></span>
<span id="cb11-80"><a href="#cb11-80" aria-hidden="true" tabindex="-1"></a>    <span class="fu">message</span>(<span class="fu">paste</span>(<span class="st">"Attention check failed for file:"</span>, file))</span>
<span id="cb11-81"><a href="#cb11-81" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb11-82"><a href="#cb11-82" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Attention check failed for file: ../data/final-data/2p9ke76o4u.csv

Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Attention check failed for file: ../data/final-data/czu8bbfh3r.csv

Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7 Columns: 20
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): stimulus, response, trial_type, plugin_version, scenario
dbl (15): rt, trial_index, time_elapsed, condition, question_order, response...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View the final combined cleaned_data tibble</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(cleaned_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 95 × 22
   condition first_scenario Justin_response_Q1 Justin_response_Q2
   &lt;fct&gt;     &lt;chr&gt;                       &lt;dbl&gt;              &lt;dbl&gt;
 1 immoral   Justin                          7                  2
 2 moral     Justin                          7                  7
 3 immoral   Justin                          7                  3
 4 moral     Nate                            7                  7
 5 moral     Justin                          7                  6
 6 immoral   Nate                            7                  3
 7 immoral   Justin                          6                  3
 8 moral     Justin                          7                  7
 9 moral     Justin                          7                  6
10 moral     Justin                          7                  7
# ℹ 85 more rows
# ℹ 18 more variables: Justin_response_Q3 &lt;dbl&gt;, Justin_response_Q4 &lt;dbl&gt;,
#   Justin_response_Q5 &lt;dbl&gt;, Justin_response_Q6 &lt;dbl&gt;,
#   Justin_response_Q7 &lt;dbl&gt;, Justin_response_Q8 &lt;dbl&gt;,
#   Justin_response_Q9 &lt;dbl&gt;, Justin_response_Q10 &lt;dbl&gt;,
#   Nate_response_Q1 &lt;dbl&gt;, Nate_response_Q2 &lt;dbl&gt;, Nate_response_Q3 &lt;dbl&gt;,
#   Nate_response_Q4 &lt;dbl&gt;, Nate_response_Q5 &lt;dbl&gt;, Nate_response_Q6 &lt;dbl&gt;, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the output path for the final cleaned CSV file</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>output_path <span class="ot">&lt;-</span> <span class="st">"../data/cleaned_data_final.csv"</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Save the final combined cleaned_data tibble as a CSV file</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(cleaned_data, output_path)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">readr.show_col_types =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="combined-data-processing" class="level4">
<h4 class="anchored" data-anchor-id="combined-data-processing">Combined Data Processing</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the combined dataset</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../data/quick_decisions_combined.csv"</span>)  <span class="co"># Read the dataset into a data frame</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="do">### Implement Exclusion Criteria: For participant with incomplete answers and lack of variance</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Process the dataset</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>cleaned_data <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 1: Filter out missing values</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">is_complete =</span> <span class="fu">complete.cases</span>(.)) <span class="sc">%&gt;%</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">complete.cases</span>(.)) <span class="sc">%&gt;%</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 2: Calculate variance for Justin and Nate</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">justin_variance =</span> <span class="fu">var</span>(<span class="fu">c</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">11</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="co"># Variance for Justin</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">nate_variance =</span> <span class="fu">var</span>(<span class="fu">c</span>(<span class="dv">12</span><span class="sc">:</span><span class="dv">22</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)          <span class="co"># Variance for Nate</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 3: Filter out participants based on variance criteria</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>(justin_variance <span class="sc">==</span> <span class="dv">0</span> <span class="sc">|</span> nate_variance <span class="sc">==</span> <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Step 4: Drop intermediate columns used for exclusion</span></span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>is_complete, <span class="sc">-</span>justin_variance, <span class="sc">-</span>nate_variance)</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: Calculate exclusion counts</span></span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>  na_exclusions_count <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dat) <span class="sc">-</span> <span class="fu">nrow</span>(dat <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">complete.cases</span>(.))) <span class="co"># Count rows with missing values</span></span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>  variance_exclusions_count <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dat <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">complete.cases</span>(.))) <span class="sc">-</span> <span class="fu">nrow</span>(cleaned_data) <span class="co"># Count participants excluded for lack of variance</span></span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>  total_exclusions <span class="ot">&lt;-</span> na_exclusions_count <span class="sc">+</span> variance_exclusions_count  <span class="co"># Calculate total exclusions</span></span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 6: Create a summary table of exclusions</span></span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>exclusions_summary <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">Exclusion_Criteria =</span> <span class="fu">c</span>(</span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Missing values (NA)"</span>,</span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Lack of variance"</span>,</span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Total exclusions"</span></span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">Count =</span> <span class="fu">c</span>(</span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a>    na_exclusions_count,</span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a>    variance_exclusions_count,</span>
<span id="cb16-41"><a href="#cb16-41" aria-hidden="true" tabindex="-1"></a>    total_exclusions</span>
<span id="cb16-42"><a href="#cb16-42" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb16-43"><a href="#cb16-43" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-44"><a href="#cb16-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-45"><a href="#cb16-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the table</span></span>
<span id="cb16-46"><a href="#cb16-46" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(exclusions_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  Exclusion_Criteria  Count
  &lt;chr&gt;               &lt;int&gt;
1 Missing values (NA)    84
2 Lack of variance        0
3 Total exclusions       84</code></pre>
</div>
</div>
</section>
<section id="manipulation-check-for-combined-dataset" class="level4">
<h4 class="anchored" data-anchor-id="manipulation-check-for-combined-dataset">Manipulation Check for Combined Dataset</h4>
<p>Groups the data by condition and provides a clear comparison of how the participants perceived Justin’s decision speed and Nate’s decision speed across the two conditions. (Note: the mean should be different between Justin and Nate but it should be similar across condition).</p>
<p>Then we will determine whether there is a statistically significant difference in the mean scores of Justin’s speed and Nate’s speed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add Participant_ID column and make it the first column</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>cleaned_data <span class="ot">&lt;-</span> cleaned_data <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Participant_ID =</span> <span class="fu">row_number</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Participant_ID, <span class="fu">everything</span>())</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>manipulation_stats <span class="ot">&lt;-</span> cleaned_data <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(condition) <span class="sc">%&gt;%</span>  <span class="co"># Group data by the 'condition' column</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_speed_justin =</span> <span class="fu">mean</span>(Justin_Q1),  <span class="co"># Mean of Justin's speed</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_speed_nate =</span> <span class="fu">mean</span>(Nate_Q1)     <span class="co"># Mean of Nate's speed</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Paired t-test for Justin's and Nate's speeds for checking whether the manipulation was successful or not </span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>manipulation_combined_t_test <span class="ot">&lt;-</span> <span class="fu">t.test</span>(</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  cleaned_data<span class="sc">$</span>Justin_Q1, </span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  cleaned_data<span class="sc">$</span>Nate_Q1, </span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">paired =</span> <span class="cn">TRUE</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(manipulation_stats)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  condition mean_speed_justin mean_speed_nate
  &lt;chr&gt;                 &lt;dbl&gt;           &lt;dbl&gt;
1 immoral                4.19            1.92
2 moral                  4.12            1.54</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(manipulation_combined_t_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  cleaned_data$Justin_Q1 and cleaned_data$Nate_Q1
t = 15.915, df = 206, p-value &lt; 2.2e-16
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 2.116230 2.714688
sample estimates:
mean difference 
       2.415459 </code></pre>
</div>
</div>
</section>
</section>
<section id="confirmatory-analysis" class="level3">
<h3 class="anchored" data-anchor-id="confirmatory-analysis">Confirmatory analysis</h3>
<p>Since the objective of this replication study was to closely mirror the original methodology, the statistical analysis replicated the 2x2 ANOVA test used in the original study. This statistical approach allowed for a direct assessment of the main effects of decision speed and moral condition on moral character evaluations, as well as their interaction, within a consistent analytical framework.</p>
<p>The 2x2 ANOVA was particularly appropriate here because it provides a straightforward method for comparing group means across these two factors, making it ideal for testing the original hypotheses about how decision speed and moral outcome influence moral judgments. By using the same statistical test as the original study, we ensured that any differences in results could be attributed to sample or context rather than methodological inconsistencies.</p>
<p>To enhance the robustness of our findings, we performed the analysis on both the combined dataset (aggregated across all three teams) and our team-specific dataset. The combined dataset allowed us to evaluate the generalizability of the findings across a more diverse sample while maintaining alignment with the target sample size of 300. The team-specific dataset, on the other hand, allowed us to ensure that any patterns observed in the combined analysis were consistent with those from our independently collected data.</p>
<p>While other methods, such as a linear mixed-effects model, could offer flexibility, the 2x2 ANOVA preserves the simplicity and interpretability central to the original study’s analysis. By using this approach, we stay true to the original design and ensure consistency in our replication study.</p>
<section id="confirmatory-analysis-for-combined-dataset" class="level4">
<h4 class="anchored" data-anchor-id="confirmatory-analysis-for-combined-dataset">Confirmatory Analysis for Combined Dataset</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 1: Calculate Average Scores for Justin and Nate</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>character_eval_combined <span class="ot">&lt;-</span> cleaned_data <span class="sc">%&gt;%</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the average score for Justin across selected questions</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">quick_justin_score =</span> <span class="fu">rowMeans</span>(<span class="fu">select</span>(., Justin_Q2, Justin_Q3, Justin_Q4)),</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the average score for Nate across selected questions</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">slow_nate_score =</span> <span class="fu">rowMeans</span>(<span class="fu">select</span>(., Nate_Q2, Nate_Q3, Nate_Q4))</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 2: Summarize Average Scores by Condition</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Group data by condition for comparison of Justin's moral character evaluation and Nate's character evaluation across condition.</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a> character_eval_combined_stats <span class="ot">&lt;-</span> character_eval_combined <span class="sc">%&gt;%</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(condition) <span class="sc">%&gt;%</span>  <span class="co"># Group data by the 'condition' column</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_justin =</span> <span class="fu">mean</span>(quick_justin_score), <span class="co"># Mean of Justin's character evaluation</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_nate =</span> <span class="fu">mean</span>(slow_nate_score)     <span class="co"># Mean of Nate's character evaluation</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 3: Reshape Data for ANOVA</span></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>character_eval_combined_long <span class="ot">&lt;-</span> character_eval_combined <span class="sc">%&gt;%</span></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(quick_justin_score, slow_nate_score), <span class="co"># Select the new columns</span></span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"speed"</span>,                           <span class="co"># Create a column for speed</span></span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"score"</span>                            <span class="co"># Create a column for scores</span></span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">speed =</span> <span class="fu">ifelse</span>(speed <span class="sc">==</span> <span class="st">"quick_justin_score"</span>, <span class="st">"Justin"</span>, <span class="st">"Nate"</span>) <span class="co"># Relabel speed column</span></span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a>  )  <span class="sc">%&gt;%</span></span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Participant_ID, condition, speed, score) <span class="co"># Keep only essential columns</span></span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 4: Run Repeated-Measures ANOVA</span></span>
<span id="cb22-38"><a href="#cb22-38" aria-hidden="true" tabindex="-1"></a>anova_combined <span class="ot">&lt;-</span> <span class="fu">aov</span>(score <span class="sc">~</span> condition <span class="sc">*</span> speed <span class="sc">+</span> <span class="fu">Error</span>(Participant_ID<span class="sc">/</span>speed), <span class="at">data =</span> character_eval_combined_long)</span>
<span id="cb22-39"><a href="#cb22-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-40"><a href="#cb22-40" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(character_eval_combined_stats) <span class="co">#Descriptive Stats</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  condition mean_justin mean_nate
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;
1 immoral          3.01      4.36
2 moral            6.17      4.75</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_combined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: Participant_ID
          Df Sum Sq Mean Sq
condition  1  2.109   2.109

Error: Participant_ID:speed
      Df  Sum Sq Mean Sq
speed  1 0.01332 0.01332

Error: Within
                 Df Sum Sq Mean Sq F value Pr(&gt;F)    
condition         1  324.1   324.1 312.655 &lt;2e-16 ***
speed             1    0.1     0.1   0.053  0.819    
condition:speed   1  198.2   198.2 191.208 &lt;2e-16 ***
Residuals       408  422.9     1.0                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="confirmatory-analysis-of-group-3s-data" class="level4">
<h4 class="anchored" data-anchor-id="confirmatory-analysis-of-group-3s-data">Confirmatory Analysis of Group 3’s data</h4>
<p>This analysis focuses on a subset of the data, specifically Group 3. We will perform the same 2 (moral condition: moral vs.&nbsp;immoral) x 2 (decision speed: quick vs.&nbsp;slow) ANOVA as in the full dataset but restricted to Group 3. This allows us to assess whether the observed effects are consistent within this specific subset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Sub setting the data</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>g3_cleaned_data <span class="ot">&lt;-</span> cleaned_data <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(group <span class="sc">==</span> <span class="dv">3</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 1: Calculate Average Scores for Justin and Nate</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>character_eval_group3 <span class="ot">&lt;-</span> g3_cleaned_data <span class="sc">%&gt;%</span> </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the average score for Justin across selected questions</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">quick_justin_score =</span> <span class="fu">rowMeans</span>(<span class="fu">select</span>(., Justin_Q2, Justin_Q3, Justin_Q4)),</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the average score for Nate across selected questions</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">slow_nate_score =</span> <span class="fu">rowMeans</span>(<span class="fu">select</span>(., Nate_Q2, Nate_Q3, Nate_Q4))</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 2: Summarize Average Scores by Condition</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Group data by condition for comparison of Justin's moral character evaluation and Nate's character evaluation across condition</span></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a> character_eval_group3_stats <span class="ot">&lt;-</span> character_eval_group3 <span class="sc">%&gt;%</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(condition) <span class="sc">%&gt;%</span>  <span class="co"># Group data by the 'condition' column</span></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_justin =</span> <span class="fu">mean</span>(quick_justin_score), <span class="co"># Mean of Justin's character evaluation</span></span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_nate =</span> <span class="fu">mean</span>(slow_nate_score)     <span class="co"># Mean of Nate's character evaluation</span></span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 3: Reshape Data for ANOVA</span></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a>character_eval_group3_long <span class="ot">&lt;-</span> character_eval_group3 <span class="sc">%&gt;%</span></span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(quick_justin_score, slow_nate_score), <span class="co"># Select the new columns</span></span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"speed"</span>,                           <span class="co"># Create a column for speed</span></span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"score"</span>                            <span class="co"># Create a column for scores</span></span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb26-33"><a href="#cb26-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-34"><a href="#cb26-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">speed =</span> <span class="fu">ifelse</span>(speed <span class="sc">==</span> <span class="st">"quick_justin_score"</span>, <span class="st">"Justin"</span>, <span class="st">"Nate"</span>) <span class="co"># Relabel speed column</span></span>
<span id="cb26-35"><a href="#cb26-35" aria-hidden="true" tabindex="-1"></a>  )  <span class="sc">%&gt;%</span></span>
<span id="cb26-36"><a href="#cb26-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Participant_ID, condition, speed, score) <span class="co"># Keep only essential columns</span></span>
<span id="cb26-37"><a href="#cb26-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-38"><a href="#cb26-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-39"><a href="#cb26-39" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 4: Run Repeated-Measures ANOVA</span></span>
<span id="cb26-40"><a href="#cb26-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-41"><a href="#cb26-41" aria-hidden="true" tabindex="-1"></a>anova_group3 <span class="ot">&lt;-</span> <span class="fu">aov</span>(score <span class="sc">~</span> condition <span class="sc">*</span> speed <span class="sc">+</span> <span class="fu">Error</span>(Participant_ID<span class="sc">/</span>speed), <span class="at">data =</span> character_eval_group3_long)</span>
<span id="cb26-42"><a href="#cb26-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-43"><a href="#cb26-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-44"><a href="#cb26-44" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(character_eval_group3_stats) <span class="co">#Descriptive Stats</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  condition mean_justin mean_nate
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;
1 immoral          3.15      4.44
2 moral            6.10      4.59</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_group3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: Participant_ID
          Df Sum Sq Mean Sq
condition  1  4.634   4.634

Error: Participant_ID:speed
      Df  Sum Sq Mean Sq
speed  1 0.09317 0.09317

Error: Within
                 Df Sum Sq Mean Sq F value Pr(&gt;F)    
condition         1 112.75  112.75 113.878 &lt;2e-16 ***
speed             1   4.96    4.96   5.011 0.0264 *  
condition:speed   1  91.71   91.71  92.628 &lt;2e-16 ***
Residuals       184 182.18    0.99                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="visualization" class="level4">
<h4 class="anchored" data-anchor-id="visualization">Visualization</h4>
<p>Note: The original study’s visualization were grouped by the condition. However, grouping by decision speed (fast vs.&nbsp;slow) may provide a clearer contrast in the interaction effect, particularly since the speed is hypothesized to influence the outcomes differently across conditions.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(character_eval_combined_long, <span class="fu">aes</span>(<span class="at">x =</span> speed, <span class="at">y =</span> score, <span class="at">fill =</span> condition)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">stat =</span> <span class="st">"summary"</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="st">"mean"</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.6</span>),  <span class="co"># Columns closer together</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.5</span>                             <span class="co"># Narrower columns</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Moral Character Evaluations (Combined Data)"</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Decision Speed (Justin / Nate)"</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean Score (Likert Scale)"</span>,  <span class="co"># Updated y-axis label</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Moral Condition"</span>          <span class="co"># Legend title for conditions</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),   <span class="co"># Adjust x-axis labels</span></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">r =</span> <span class="dv">15</span>)),  <span class="co"># Add spacing to y-axis title</span></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">t =</span> <span class="dv">10</span>))   <span class="co"># Add spacing to x-axis title</span></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"moral"</span> <span class="ot">=</span> <span class="st">"#4F81BD"</span>, <span class="st">"immoral"</span> <span class="ot">=</span> <span class="st">"#9DC3E6"</span>),  <span class="co"># Two shades for moral/immoral</span></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"moral"</span> <span class="ot">=</span> <span class="st">"Moral"</span>, <span class="st">"immoral"</span> <span class="ot">=</span> <span class="st">"Immoral"</span>)     <span class="co"># Custom legend labels</span></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7</span>),  <span class="co"># Y-axis limits for Likert scale</span></span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>,      <span class="co"># Label y-axis by 1's</span></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)   <span class="co"># No extra space above/below</span></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="emily_han_writeup_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(character_eval_group3_long, <span class="fu">aes</span>(<span class="at">x =</span> speed, <span class="at">y =</span> score, <span class="at">fill =</span> condition)) <span class="sc">+</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">stat =</span> <span class="st">"summary"</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="st">"mean"</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.6</span>),  <span class="co"># Columns closer together</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.5</span>                             <span class="co"># Narrower columns</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Moral Character Evaluations (Group 3 Data)"</span>,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Decision Speed (Justin / Nate)"</span>,    <span class="co"># Updated x-axis label</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean Score (Likert Scale)"</span>,         <span class="co"># Updated y-axis label</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Moral Condition"</span>                <span class="co"># Legend title for conditions</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>),  <span class="co"># Centered title</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),   <span class="co"># Adjust x-axis labels</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">r =</span> <span class="dv">15</span>)),  <span class="co"># Add spacing to y-axis title</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">t =</span> <span class="dv">10</span>))   <span class="co"># Add spacing to x-axis title</span></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"moral"</span> <span class="ot">=</span> <span class="st">"#4F81BD"</span>, <span class="st">"immoral"</span> <span class="ot">=</span> <span class="st">"#9DC3E6"</span>),  <span class="co"># Two shades for moral/immoral</span></span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"moral"</span> <span class="ot">=</span> <span class="st">"Moral"</span>, <span class="st">"immoral"</span> <span class="ot">=</span> <span class="st">"Immoral"</span>)     <span class="co"># Custom legend labels</span></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7</span>),  <span class="co"># Y-axis limits for Likert scale</span></span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>,      <span class="co"># Label y-axis by 1's</span></span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)   <span class="co"># No extra space above/below</span></span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="emily_han_writeup_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="exploratory-analysis" class="level1">
<h1>Exploratory Analysis</h1>
<section id="analysis-on-perceived-certainty" class="level2">
<h2 class="anchored" data-anchor-id="analysis-on-perceived-certainty">Analysis on perceived certainty</h2>
<p>The aim of this analysis is to perform a <strong>2 (moral condition: moral vs.&nbsp;immoral) x 2 (decision speed: quick vs.&nbsp;slow)</strong> repeated-measures ANOVA to compare group means for decision certainty evaluations of Justin and Nate.</p>
<p>Items accounting for decision certainty evaluation (Question 5-8):</p>
<ol start="5" type="1">
<li>Would you say [name] was quite certain in his decision, or did [name] have hesitations about his decision? (1 = completely certain, 7 = considerable hesitations)</li>
<li>How close do you think [name] was to choosing the alternate course of action? (1 = very close to, 7 = not close at all)</li>
<li>How conflicted do you think [name] felt in making the decision? (1 = very conflicted, 7 = not at all conflicted)</li>
<li>Based on the information provided, do you think [name] had many reservations about the decision? (1 = none at all, 7 = a whole lot)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 1: Calculate Average Scores for Justin and Nate</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Since Questions 5 &amp; 8 are reverse scored, we need to reverse code those items before we proceed with further analysis  Reverse coding is performed on a 1-7 scale to align with the scoring direction. </span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># High score = higher certainty on decision </span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a> <span class="co">#1a: Subset relevant columns</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  certain_dat <span class="ot">&lt;-</span> cleaned_data[, <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, <span class="dv">7</span><span class="sc">:</span><span class="dv">10</span>, <span class="dv">17</span><span class="sc">:</span><span class="dv">20</span>, <span class="dv">23</span>)]</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="co">#1b: Reverse code Questions 5 and 8 for both Justin and Nate</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  certain_dat<span class="sc">$</span>Justin_Q5R <span class="ot">&lt;-</span> <span class="dv">8</span> <span class="sc">-</span> certain_dat<span class="sc">$</span>Justin_Q5  <span class="co"># Reverse code for Justin's Q5</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  certain_dat<span class="sc">$</span>Justin_Q8R <span class="ot">&lt;-</span> <span class="dv">8</span> <span class="sc">-</span> certain_dat<span class="sc">$</span>Justin_Q8  <span class="co"># Reverse code for Justin's Q8</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  certain_dat<span class="sc">$</span>Nate_Q5R <span class="ot">&lt;-</span> <span class="dv">8</span> <span class="sc">-</span> certain_dat<span class="sc">$</span>Nate_Q5      <span class="co"># Reverse code for Nate's Q5</span></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>  certain_dat<span class="sc">$</span>Nate_Q8R <span class="ot">&lt;-</span> <span class="dv">8</span> <span class="sc">-</span> certain_dat<span class="sc">$</span>Nate_Q8      <span class="co"># Reverse code for Nate's Q8</span></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  <span class="co">#1c: Calculate combined certainty scores </span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>  certain_eval_combined <span class="ot">&lt;-</span> certain_dat <span class="sc">%&gt;%</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">quick_justin_score =</span> <span class="fu">rowMeans</span>(<span class="fu">select</span>(., Justin_Q5R, Justin_Q6, Justin_Q7, Justin_Q8R), <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">slow_nate_score =</span> <span class="fu">rowMeans</span>(<span class="fu">select</span>(., Nate_Q5R, Nate_Q6, Nate_Q7, Nate_Q8R), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 2: Summarize Average Scores by Condition</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Group data by condition for comparison of Justin's decision certainty evaluation and Nate's decision certainty evaluation across condition</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a>certain_eval_combined_stats <span class="ot">&lt;-</span> certain_eval_combined <span class="sc">%&gt;%</span></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(condition) <span class="sc">%&gt;%</span>  <span class="co"># Group data by the 'condition' column</span></span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_justin =</span> <span class="fu">mean</span>(quick_justin_score), <span class="co"># Mean of Justin's character evaluation</span></span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_nate =</span> <span class="fu">mean</span>(slow_nate_score)     <span class="co"># Mean of Nate's character evaluation</span></span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 3: Reshape Data for ANOVA</span></span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>certain_eval_combined_long <span class="ot">&lt;-</span> certain_eval_combined <span class="sc">%&gt;%</span></span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> <span class="fu">c</span>(quick_justin_score, slow_nate_score), <span class="co"># Select the new columns</span></span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"speed"</span>,                           <span class="co"># Create a column for speed</span></span>
<span id="cb32-40"><a href="#cb32-40" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"score"</span>                            <span class="co"># Create a column for scores</span></span>
<span id="cb32-41"><a href="#cb32-41" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb32-42"><a href="#cb32-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb32-43"><a href="#cb32-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">speed =</span> <span class="fu">ifelse</span>(speed <span class="sc">==</span> <span class="st">"quick_justin_score"</span>, <span class="st">"Justin"</span>, <span class="st">"Nate"</span>) <span class="co"># Relabel speed column</span></span>
<span id="cb32-44"><a href="#cb32-44" aria-hidden="true" tabindex="-1"></a>  )  <span class="sc">%&gt;%</span></span>
<span id="cb32-45"><a href="#cb32-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Participant_ID, condition, speed, score) <span class="co"># Keep only essential columns</span></span>
<span id="cb32-46"><a href="#cb32-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-47"><a href="#cb32-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-48"><a href="#cb32-48" aria-hidden="true" tabindex="-1"></a><span class="do">### Step 4: Run Repeated-Measures ANOVA</span></span>
<span id="cb32-49"><a href="#cb32-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-50"><a href="#cb32-50" aria-hidden="true" tabindex="-1"></a>anova_certain_combined <span class="ot">&lt;-</span> <span class="fu">aov</span>(score <span class="sc">~</span> condition <span class="sc">*</span> speed <span class="sc">+</span> <span class="fu">Error</span>(Participant_ID<span class="sc">/</span>speed), <span class="at">data =</span> certain_eval_combined_long)</span>
<span id="cb32-51"><a href="#cb32-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-52"><a href="#cb32-52" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(certain_eval_combined_stats) <span class="co">#Descriptive Stats</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  condition mean_justin mean_nate
  &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;
1 immoral          5.94      2.85
2 moral            6.07      2.84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_certain_combined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: Participant_ID
          Df Sum Sq Mean Sq
condition  1 0.5586  0.5586

Error: Participant_ID:speed
      Df Sum Sq Mean Sq
speed  1  742.7   742.7

Error: Within
                 Df Sum Sq Mean Sq F value Pr(&gt;F)    
condition         1    0.4    0.37   0.275  0.600    
speed             1  291.1  291.14 218.427 &lt;2e-16 ***
condition:speed   1    0.6    0.56   0.417  0.519    
Residuals       408  543.8    1.33                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="visualization-1" class="level3">
<h3 class="anchored" data-anchor-id="visualization-1">Visualization</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(certain_eval_combined_long, <span class="fu">aes</span>(<span class="at">x =</span> speed, <span class="at">y =</span> score, <span class="at">fill =</span> condition)) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">stat =</span> <span class="st">"summary"</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="st">"mean"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.6</span>),  <span class="co"># Columns closer together</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="fl">0.5</span>                             <span class="co"># Narrower columns</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Decision Certainty Evaluations (Combined Data)"</span>,</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Decision Speed (Justin / Nate)"</span>,    <span class="co"># Updated x-axis label</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mean Score (Likert Scale)"</span>,         <span class="co"># Updated y-axis label</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Moral Condition"</span>                <span class="co"># Legend title for conditions</span></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>),</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">"bold"</span>, <span class="at">size =</span> <span class="dv">14</span>),  <span class="co"># Centered title</span></span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),   <span class="co"># Adjust x-axis labels</span></span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">r =</span> <span class="dv">15</span>)),  <span class="co"># Add spacing to y-axis title</span></span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">margin =</span> <span class="fu">margin</span>(<span class="at">t =</span> <span class="dv">10</span>))   <span class="co"># Add spacing to x-axis title</span></span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"moral"</span> <span class="ot">=</span> <span class="st">"#4F81BD"</span>, <span class="st">"immoral"</span> <span class="ot">=</span> <span class="st">"#9DC3E6"</span>),  <span class="co"># Two shades for moral/immoral</span></span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"moral"</span> <span class="ot">=</span> <span class="st">"Moral"</span>, <span class="st">"immoral"</span> <span class="ot">=</span> <span class="st">"Immoral"</span>)     <span class="co"># Custom legend labels</span></span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7</span>),  <span class="co"># Y-axis limits for Likert scale</span></span>
<span id="cb36-28"><a href="#cb36-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>,      <span class="co"># Label y-axis by 1's</span></span>
<span id="cb36-29"><a href="#cb36-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)   <span class="co"># No extra space above/below</span></span>
<span id="cb36-30"><a href="#cb36-30" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="emily_han_writeup_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="post-hoc-effect-size-calculation" class="level2">
<h2 class="anchored" data-anchor-id="post-hoc-effect-size-calculation">Post Hoc &amp; Effect size calculation</h2>
<p>Post-hoc and effect size analyses were conducted using a mixed-effects model to account for participant variability and potential unbalanced data. The model included the same fixed effects structure (condition, speed, and their interaction) as the repeated measures ANOVA.</p>
<section id="effect-size-calculation-on-both-moral-character-evaluation-decision-certainty-evaluation-tests" class="level3">
<h3 class="anchored" data-anchor-id="effect-size-calculation-on-both-moral-character-evaluation-decision-certainty-evaluation-tests">Effect Size Calculation on both Moral Character Evaluation &amp; Decision Certainty Evaluation tests</h3>
<section id="moral-character-evaluation-1" class="level4">
<h4 class="anchored" data-anchor-id="moral-character-evaluation-1">Moral Character Evaluation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combined Data</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Refit the repeated measures model</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>anova_combined_lmer <span class="ot">&lt;-</span> <span class="fu">lmer</span>(</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  score <span class="sc">~</span> condition <span class="sc">*</span> speed <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Participant_ID),</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> character_eval_combined_long</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate partial eta-squared for the mixed-effects model</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>eta2_combined <span class="ot">&lt;-</span> <span class="fu">eta_squared</span>(anova_combined_lmer, <span class="at">partial =</span> <span class="cn">TRUE</span>)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(eta2_combined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type III)

Parameter       | Eta2 (partial) |       95% CI
-----------------------------------------------
condition       |           0.54 | [0.47, 1.00]
speed           |       7.21e-04 | [0.00, 1.00]
condition:speed |           0.58 | [0.51, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Group 3 Data</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Refit the repeated measures model</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>anova_group3_lmer <span class="ot">&lt;-</span> <span class="fu">lmer</span>(</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  score <span class="sc">~</span> condition <span class="sc">*</span> speed <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Participant_ID),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> character_eval_group3_long</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate partial eta-squared for the mixed-effects model</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>eta2_group3 <span class="ot">&lt;-</span> <span class="fu">eta_squared</span>(anova_group3_lmer, <span class="at">partial =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(eta2_group3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type III)

Parameter       | Eta2 (partial) |       95% CI
-----------------------------------------------
condition       |           0.48 | [0.36, 1.00]
speed           |       9.18e-03 | [0.00, 1.00]
condition:speed |           0.59 | [0.48, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
</section>
<section id="decision-certainty-evaluation" class="level4">
<h4 class="anchored" data-anchor-id="decision-certainty-evaluation">Decision Certainty Evaluation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Refit the repeated measures model</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>anova_certain_combined_lmer <span class="ot">&lt;-</span> <span class="fu">lmer</span>(</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  score <span class="sc">~</span> condition <span class="sc">*</span> speed <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> Participant_ID),</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> certain_eval_combined_long</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>boundary (singular) fit: see help('isSingular')</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate partial eta-squared for the mixed-effects model</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>eta2_certain_combined <span class="ot">&lt;-</span> <span class="fu">eta_squared</span>(anova_certain_combined_lmer, <span class="at">partial =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(eta2_certain_combined)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type III)

Parameter       | Eta2 (partial) |       95% CI
-----------------------------------------------
condition       |       7.46e-04 | [0.00, 1.00]
speed           |           0.65 | [0.61, 1.00]
condition:speed |       8.72e-04 | [0.00, 1.00]

- One-sided CIs: upper bound fixed at [1.00].</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="post-hoc-comparison-of-all-three-2x2-anova-tests" class="level2">
<h2 class="anchored" data-anchor-id="post-hoc-comparison-of-all-three-2x2-anova-tests">Post-Hoc Comparison of all three 2x2 Anova Tests</h2>
<p>Post-Hoc Pairwise Comparisons on both Moral Character Evaluation &amp; Decision Certainty Evaluation tests</p>
<section id="moral-character-evaluation-2" class="level4">
<h4 class="anchored" data-anchor-id="moral-character-evaluation-2">Moral Character Evaluation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combined Data: post hoc pairwise comparisons using estimated marginal means</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>posthoc_results <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(anova_combined_lmer, pairwise <span class="sc">~</span> condition <span class="sc">*</span> speed)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(posthoc_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 condition speed  emmean     SE  df lower.CL upper.CL
 immoral   Justin   3.01 0.0987 373     2.81     3.20
 moral     Justin   6.17 0.1010 373     5.97     6.36
 immoral   Nate     4.36 0.0987 373     4.16     4.55
 moral     Nate     4.75 0.1010 373     4.55     4.95

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 

$contrasts
 contrast                      estimate    SE  df t.ratio p.value
 immoral Justin - moral Justin   -3.159 0.141 373 -22.352  &lt;.0001
 immoral Justin - immoral Nate   -1.352 0.116 205 -11.699  &lt;.0001
 immoral Justin - moral Nate     -1.743 0.141 373 -12.333  &lt;.0001
 moral Justin - immoral Nate      1.807 0.141 373  12.783  &lt;.0001
 moral Justin - moral Nate        1.416 0.118 205  11.958  &lt;.0001
 immoral Nate - moral Nate       -0.391 0.141 373  -2.765  0.0304

Degrees-of-freedom method: kenward-roger 
P value adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group 3 Data: post hoc pairwise comparisons using estimated marginal means</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>posthoc_group3_results <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(anova_group3_lmer, pairwise <span class="sc">~</span> condition <span class="sc">*</span> speed)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(posthoc_group3_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 condition speed  emmean    SE  df lower.CL upper.CL
 immoral   Justin   3.15 0.146 170     2.87     3.44
 moral     Justin   6.10 0.147 170     5.81     6.39
 immoral   Nate     4.44 0.146 170     4.15     4.72
 moral     Nate     4.59 0.147 170     4.30     4.88

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 

$contrasts
 contrast                      estimate    SE  df t.ratio p.value
 immoral Justin - moral Justin   -2.947 0.207 170 -14.238  &lt;.0001
 immoral Justin - immoral Nate   -1.285 0.171  93  -7.504  &lt;.0001
 immoral Justin - moral Nate     -1.436 0.207 170  -6.938  &lt;.0001
 moral Justin - immoral Nate      1.662 0.207 170   8.030  &lt;.0001
 moral Justin - moral Nate        1.511 0.173  93   8.731  &lt;.0001
 immoral Nate - moral Nate       -0.151 0.207 170  -0.730  0.8848

Degrees-of-freedom method: kenward-roger 
P value adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
</div>
</section>
<section id="decision-certainty-evaluation-1" class="level4">
<h4 class="anchored" data-anchor-id="decision-certainty-evaluation-1">Decision Certainty Evaluation</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conduct post hoc pairwise comparisons using estimated marginal means</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>posthoc_certain_results <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(anova_certain_combined_lmer, pairwise <span class="sc">~</span> condition <span class="sc">*</span> speed)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(posthoc_certain_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
 condition speed  emmean    SE  df lower.CL upper.CL
 immoral   Justin   5.94 0.112 410     5.72     6.16
 moral     Justin   6.07 0.115 410     5.84     6.30
 immoral   Nate     2.85 0.112 410     2.63     3.07
 moral     Nate     2.84 0.115 410     2.62     3.07

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 

$contrasts
 contrast                      estimate    SE  df t.ratio p.value
 immoral Justin - moral Justin -0.13063 0.160 410  -0.814  0.8478
 immoral Justin - immoral Nate  3.09198 0.158 205  19.508  &lt;.0001
 immoral Justin - moral Nate    3.09709 0.160 410  19.303  &lt;.0001
 moral Justin - immoral Nate    3.22261 0.160 410  20.085  &lt;.0001
 moral Justin - moral Nate      3.22772 0.162 205  19.878  &lt;.0001
 immoral Nate - moral Nate      0.00511 0.160 410   0.032  1.0000

Degrees-of-freedom method: kenward-roger 
P value adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
</div>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>First, paired t-test was conducted to examine whether manipulation of decision speed was successful. As expected, Justin was rated as a faster decision maker in comparison to Nate, <em>F</em>(1, 206) = 15.915, <em>p</em> &lt; 2.2e-16, across both moral and immoral condition (whether they decided to keep or return the wallet).</p>
<p>As confirmatory analysis, 2x2 repeated measures ANOVA was conducted to examine the effects of <strong>Moral Condition</strong> (moral vs immoral) and <strong>Decision Speed</strong> (fast vs slow) on <strong>moral character evaluation</strong>.</p>
<p>The main effect of <strong>moral condition</strong> was <strong>consistent</strong> for both combined data and the subset of Group 3’s subset data. The combined data shows that there is <strong>significant main effec</strong>t of condition was found, F(1,408) = 312.66, <em>p</em> &lt;.001, highlighting a strong influence of moral condition on moral character evaluation. The subset data also shows that a <strong>significant main effect</strong> of condition F(1,184) = 113.88, <em>p</em>&lt;.001. This results suggests that the agents’ decision itself, whether to steal the money (immoral) or to return the money (moral), has significant influence on how the agents’ moral characters are perceived regardless of how fast or how slow they arrived to that decision.</p>
<p>The main effect of <strong>decision speed</strong> was <strong>not consistent;</strong> it was <strong>not</strong> <strong>significant</strong> for combined data, but it was <strong>significant</strong> for the subset of Group 3’s data. The combined data shows that there is <strong>no significant main effect</strong> of condition was found, F(1,408) = 0.053, <em>p</em> = .819. This is suggesting that regardless of the agents’ decision, moral or immoral, how fast or slow the agents’ arrive to that decision has no significant influence on how the agents’ moral character is precieved. However, the subset data suggests otherwise meaning how fast or slow the decision was made has <strong>significant effect</strong> on how the agents’ moral character is perceived, F(1,184) = 5.01, <em>p</em> = .026.</p>
<p>The interaction effect of <strong>moral condition</strong> was <strong>consistent</strong> for both combined data and the subset of Group 3’s subset data. It was <strong>significant</strong> for both combined data [F(1, 408) = 191.21, <em>p</em> &lt; .001] and the subset of Group 3’s data [F(1,184) = 92.63, <em>p</em> &lt; .001]. This confirms that decision speed (Quick vs.&nbsp;Slow) influences perception on the agents’ moral character differently depending on whether they made moral decision or immoral decision. In comparison to Nate, who made a slow decision, Justin who made quick decision will be perceived as a more moral person when he return the money and perceived as a more immoral person when he steal the money. For Nate, who made a slow decision, perception on his moral character were more <strong>neutral</strong> or less extreme, regardless of whether he made a moral or immoral decision. This suggests that decision speed amplifies perceptions of moral character for Justin, while Nate’s slower decision making leads to less polarized perception.</p>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<section id="summary-of-replication-attempt" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-replication-attempt">Summary of Replication Attempt</h3>
<p>In general, the results largely replicate the findings of the original study, particularly the strong interaction effect between moral condition and decision speed. The main effect of moral condition was consistent across both datasets, emphasizing the robust influence of decision type on moral character evaluations. However, the main effect of decision speed showed partial replication, with differences observed between the combined dataset and subset. The current study’s larger sample size may have reduced variability, particularly in the combined dataset, making it harder to detect the main effect of decision speed. Overall, the most of the results supports the conclusion that decision speed amplifies moral evaluations depending on the nature of the decision.</p>
</section>
<section id="commentary" class="level3">
<h3 class="anchored" data-anchor-id="commentary">Commentary</h3>
<p>This replication supports the interaction effect between moral condition and decision speed as a robust finding. Differences in the main effect of decision speed suggest the presence of potential moderators such as perceived certainty and variability in sample characteristics could help clarify the contextual and psychological mechanisms underlying these effects.</p>
</section>
</section>
<section id="statement-of-contributions" class="level2">
<h2 class="anchored" data-anchor-id="statement-of-contributions">Statement of Contributions</h2>
<p><strong>Asad Tariq</strong>: Conceptualization, Formal Analysis, Software, Methodology, Investigation, Data Curation, Writing</p>
<p><strong>Emily Han</strong>: Conceptualization, Formal Analysis, Software, Methodology, Investigation, Data Curation, Writing</p>
<p><strong>Erika Garza-Elorduy</strong>: Conceptualization, Formal Analysis, Investigation, Project Administration, Data Visualization, Writing</p>
<p><strong>Luna Bellitto</strong>: Conceptualization, Formal Analysis, Investigation, Methodology, Project Administration, Writing</p>
<p><strong>Janna Wennberg</strong>: Data Curation</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>